# Generated by Django 5.1.15 on 2026-03-28 08:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='タグ名')),
            ],
            options={
                'verbose_name': 'タグ',
                'verbose_name_plural': 'タグ',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Knowledge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='タイトル')),
                ('raw_input', models.TextField(help_text='ユーザーが入力する元ネタ', verbose_name='入力テキスト')),
                ('content', models.TextField(blank=True, help_text='Geminiが生成するMarkdown形式の本文', verbose_name='本文')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_items', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('tags', models.ManyToManyField(blank=True, related_name='knowledge_items', to='knowledge.tag', verbose_name='タグ')),
            ],
            options={
                'verbose_name': 'ナレッジ',
                'verbose_name_plural': 'ナレッジ',
                'ordering': ['-created_at'],
            },
        ),
    ]
